remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: John Mario Castrillon Gutierrez
submodulo: Programación de Aplicaciones Móviles I
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/jhon-84425.appspot.com/o/mia.jpeg?alt=media&token=758d763c-c2c5-420e-9881-d9d061449df8&_gl=1*wg0c23*_ga*MTIwMDQyNjI4LjE2OTYxMjc3MTk.*_ga_CW55HF8NVT*MTY5NjEyNzcxOC4xLjEuMTY5NjEyODI0OS41Mi4wLjA.

